spring:
  datasource:
    url: jdbc:postgresql://attempts-db-postgres:5433/attempts-db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: redis
    port: 6379
server:
  port: 8080

tests:
  test-url: http://test-service/api/tests/