spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      username: root
      password: root
      database: testing-subject-db
      authentication-database: admin
      auto-index-creation: true
  redis:
    host: localhost
    port: 6379
server:
  port: 0
