spring:
  datasource:
    url: jdbc:postgresql://tests-db-postgres:5432/tests-db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: redis
    port: 6379
server:
  port: 8080

subjects:
  subject-url: http://subject-service/api/subjects/
