spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tests-db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 0

subjects:
  subject-url: http://subject-service/api/subjects/