apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  selector:
    matchLabels:
      app: config-service
  replicas: 1
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: vitaliipsl/testing-config-service:3
          ports:
            - containerPort: 8071
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  selector:
    app: config-service
  type: LoadBalancer
  ports:
    - name: http
      port: 8071
      targetPort: 8071
