apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: vitaliipsl/testing-gateway-service:3
          ports:
            - containerPort: 8072
          env:
          - name: CONFIG_SERVICE_URL
            value: http://config-service:8071
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  type: LoadBalancer
  ports:
    - name: http
      port: 8072
      targetPort: 8072
      nodePort: 30000
