apiVersion: apps/v1
kind: Deployment
metadata:
  name: subjects-db-mongodb
spec:
  selector:
    matchLabels:
      app: subjects-db-mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: subjects-db-mongodb
    spec:
      containers:
        - name: subjects-db-mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: subjects-db-mongodb
spec:
  selector:
    app: subjects-db-mongodb
  ports:
    - name: http
      port: 27018
      targetPort: 27017
  type: NodePort
