apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  selector:
    matchLabels:
      app: users-service
  replicas: 1
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: vitaliipsl/testing-user-service:3
          ports:
            - containerPort: 8080
          env:
          - name: CONFIG_SERVICE_URL
            value: http://config-service:8071
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-service
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30002
