apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-db-mongodb
spec:
  selector:
    matchLabels:
      app: users-db-mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: users-db-mongodb
    spec:
      containers:
        - name: users-db-mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: users-db-mongodb
spec:
  selector:
    app: users-db-mongodb
  ports:
  - name: http
    port: 27017
    targetPort: 27017

